general {
    colors = true
    interval = 2
    color_good = "#00FF00"
    color_degraded = "#FFFF00"
    color_bad = "#FF0000"
}

order += "disk /"
order += "memory"
order += "cpu_usage"
order += "ethernet _first_"
order += "tztime local"

disk "/" {
    format = "  DISCO: %used / %avail "
}

memory {
    format = "  RAM: %used / %total "
    threshold_degraded = "10%"
    format_degraded = "MEMORY LOW: %free"
}

cpu_usage {
    format = "  CPU: %usage "
}

ethernet _first_ {
    format_up = " 󰈀 %interface: %ip "
    format_down = " 󰈀 DOWN "
}

tztime local {
    format = "  %d-%m-%Y   %H:%M:%S "
}
